spring.application.name=nameserver

server.port=8761

# O server nao se auto registrar no discovery
eureka.client.register-with-eureka=false

# Nao baixar a lista de servidores eureka - o proprio serviço é responsavel por mante-la/gerencia-la
eureka.client.fetch-registry=false

# Indicar para o servidor registrar o IP do serviço e nao o nome do dominio
eureka.instance.prefer-ip-address=true
