###
@urlServer = http://localhost:4000

###
GET {{urlServer}}/events

###
POST {{urlServer}}/events
Content-Type: application/json

{
  "description": "Curso Spring JPA",
  "dateTime": "2025-12-20T18:00:00",
  "startingSales": "2025-12-10T20:00:00",
  "endingSales": "2025-12-19T23:59:59",
  "price": 1500
}

###
GET {{urlServer}}/sales

###
POST {{urlServer}}/sales
Content-Type: application/json

{
  "eventId": "94facfad-2c94-43e3-aac3-5f1472cfe568",
  "userId": "8c66c443-509a-41a5-bf6d-9d795a978584"
}