spring.application.name=users-service

# Porta do servidor
server.port=3000

# Configuração do banco de dados (IP:porta/db)
spring.datasource.url=jdbc:postgresql://localhost:9876/tickets-users
spring.datasource.username=pg-tickets-users
spring.datasource.password=tickets-users-password

# Definição para que o JPA gerencie a estrutura das entidades no BD
spring.jpa.hibernate.ddl-auto=update
