###
@urlServer = http://localhost:3000

###
GET {{urlServer}}/users/status

###
GET {{urlServer}}/ccn

###
POST {{urlServer}}/ccn
Content-Type: application/json

{
  "name": ""
}

###
GET {{urlServer}}/users

###
POST {{urlServer}}/users
Content-Type: application/json

{
  "name": "Israel",
  "email": "israel@example.com",
  "password": "123456",
  "creditCardNetworkId": "4a6b3e45-21cb-4a8f-809b-12454f59019e"
}